dist: trusty

language: python
python:
  - "2.7"
  - "3.6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.12.0/bazel_0.12.0-linux-x86_64.deb
  - sha256sum -c tools/bazel_0.12.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.12.0-linux-x86_64.deb

script:
  # Dumb tests for NumPy API version errors.
  - python -c 'import numpy'
  - python -c 'import pandas'
  - python -c 'import scipy'
  - python -c 'import tensorflow'
  # End-to-end tests must be marked "large". They exceed Travis CI's 3GB RAM
  # limit.
  - bazel test --test_output=errors --test_size_filters=small,medium //moonlight/...
