dist: trusty

language: python
python:
  - "2.7"
  - "3.6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.12.0/bazel_0.12.0-linux-x86_64.deb
  - sha256sum -c tools/bazel_0.12.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.12.0-linux-x86_64.deb

script:
  - tools/travis_tests.sh
